version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - echo test pour voir si ca marchera test
  pre_build:
    commands:
      - echo start prebuild and end it    
  build:
    commands:
      - echo Running buuild
  post_build:
    commands:
      - echo Build completed successfully.

artifacts:
  files:
    - "**/*"
  base-directory: .  # Specify where artifacts are stored
